[package]
name = "winit_event_helper"
version = "0.1.0"
edition = "2021"
description = "A crate for easy winit event handling using callback functions. (Inspired by winit_input_helper.)"
license = "MIT"
repository = "https://github.com/IvoteSligte/winit_event_helper/"
categories = ["no-std"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["std"]
std = []

[dependencies]
ahash = "0.8.0"
winit = "0.27.2"
